# Generated by Django 3.1.2 on 2020-12-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
    ]
