# Generated by Django 3.1.2 on 2020-12-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201202_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-likes_num']},
        ),
    ]
