# Generated by Django 3.1.2 on 2020-12-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20201202_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='posted_by',
        ),
    ]
