# Generated by Django 3.1.2 on 2020-12-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_comment_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time_sent',
        ),
    ]
