# Generated by Django 3.1.2 on 2020-12-08 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_message_time_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
