# Generated by Django 3.1.2 on 2020-12-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_message_time_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_private',
        ),
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
