# Generated by Django 3.1.2 on 2020-12-14 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20201212_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
