# Generated by Django 3.1.2 on 2020-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20201214_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_page',
            field=models.BooleanField(default=False),
        ),
    ]
